version: '3'

services:
  search-app:
    build: .
    ports:
      - "5030:5000"
    environment:
      - PORT=5000
      # 智谱AI配置
      - ZHIPUAI_API_KEY=${ZHIPUAI_API_KEY}
      - ZHIPUAI_API_URL=${ZHIPUAI_API_URL}
      - ZHIPUAI_MODEL=${ZHIPUAI_MODEL}
      - ZHIPUAI_TEMPERATURE=${ZHIPUAI_TEMPERATURE}
      - ZHIPUAI_TOP_P=${ZHIPUAI_TOP_P}
      # DeepSeek配置
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_API_URL=${DEEPSEEK_API_URL}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL}
      - DEEPSEEK_TEMPERATURE=${DEEPSEEK_TEMPERATURE}
      - DEEPSEEK_TOP_P=${DEEPSEEK_TOP_P}
      # Bocha AI配置
      - BOCHAAI_API_KEY=${BOCHAAI_API_KEY}
      - BOCHAAI_API_URL=${BOCHAAI_API_URL}
      - BOCHAAI_DEFAULT_FRESHNESS=${BOCHAAI_DEFAULT_FRESHNESS}
      # SearXNG配置
      - SEARXNG_API_HOST=${SEARXNG_API_HOST}
      - SEARXNG_DEFAULT_LANGUAGE=${SEARXNG_DEFAULT_LANGUAGE}
      - SEARXNG_DEFAULT_SAFESEARCH=${SEARXNG_DEFAULT_SAFESEARCH}
      - SEARXNG_DEFAULT_ENGINES=${SEARXNG_DEFAULT_ENGINES}
      - SEARXNG_DEFAULT_TIME_RANGE=${SEARXNG_DEFAULT_TIME_RANGE}
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
